# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- dev

pool:
  name: API_POOL

jobs:

- job: Build
  displayName: 'Build job'
  steps:

  - script: |
      git checkout dev
      cd ./'NextJS Proyect'
      touch .env.temp
      echo "NEXT_PUBLIC_PROTOCOL=$(NEXT_PUBLIC_PROTOCOL)" >> .env.temp  
      echo "NEXT_PUBLIC_HOST=$(NEXT_PUBLIC_HOST)" >> .env.temp  
      echo "KEY=$(KEY)" >> .env.temp  
      echo "NEXT_PUBLIC_HLS_PORT=$(NEXT_PUBLIC_HLS_PORT)" >> .env.temp  
      echo "NEXT_PUBLIC_API_PORT=$(NEXT_PUBLIC_API_PORT)" >> .env.temp  
      echo "NEXT_PUBLIC_WEB_PORT=$(NEXT_PUBLIC_WEB_PORT)" >> .env.temp  
      echo "NEXT_PUBLIC_RMTP_PORT=$(NEXT_PUBLIC_RMTP_PORT)" >>  .env.temp  
      cp -f .env.temp .env.local
      cat .env.local
      npm install
      npm install pm2 --force 
      npm run build
      npm run start
    displayName: 'npm install and build'
    