# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- dev

pool:
  name: API_POOL

jobs:

- job: Build
  displayName: 'Build job'
  steps:

  - script: |
      git checkout dev
      cd api
      touch .env.temp
      echo "API_PORT=$API_PORT" >> .env.temp
      echo "MONGODB_URI=$(MONGODB_URI)" >> .env.temp
      echo "MONGODB_HOST=$MONGODB_HOST" >> .env.temp
      echo "MONGODB_PORT=$MONGODB_PORT" >> .env.temp
      echo "MONGODB_USER=$MONGODB_USER" >> .env.temp
      echo "MONGODB_PASSWORD=$MONGODB_PASSWORD" >> .env.temp
      echo "MONGODB_NAME=$MONGODB_NAME" >> .env.temp
      echo "JWT_SECRET=$JWT_SECRET" >> .env.temp
      cp -f .env.temp .env
      cat .env
      npm install
      npm install pm2 --force 
      npm run build
      npm run start:prod 
    displayName: 'npm install and build'
    